### ISSUE TITLE
improve speed of turnover recording

### ISSUE THREAD

**Issue by Felix11H** [syn-lt/network_x10#5]
from @mstimberg on [brian mailing list](https://groups.google.com/forum/#!topic/briansupport/2V3782xCxZU):

> I don't see anything obvious to improve, maybe opening/closing the file for each line you add slows things down? I think you could open it only once by defining a local static variable in your function:
> 
>     static std::ofstream outfile("spk_register", std::ios_base::app);
>

**Comment by felix11h** [comment]
I tried this, it lead to errors where different network objects were writing into the same file. Closing this for now.
